name: "Free Disk Space (Ubuntu)"
description: "A Simple Action to Free Up Disk Space on GitHub Hosted Runners"

branding:
  icon: "command"
  color: "gray-dark"

inputs:
  android:
    description: "Remove Android runtime"
    required: false
    default: "true"
# outputs:
#   saved-space:
#     description: "The amount of space saved"
#     value: ${{ steps.free-disk-space.outputs.saved-space }}

runs:
  using: "composite"
  steps:

    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - shell: bash
      name: "Free Disk Space"
      id: free-disk-space
      run: main.sh
      env:
        ANDROID_FILES: ${{ inputs.android }}