name: "Free Disk Space (Ubuntu)"
description: "A Simple Action to Free Up Disk Space on GitHub Hosted Runners"
author: "Enderson Menezes <mail@enderson.dev>"

branding:
  icon: "command"
  color: "gray-dark"

inputs:
  principal_dir:
    description: "Principal Directory Mount Point"
    required: false
    default: "/"
  remove_android:
    description: "Remove Android Files"
    required: false
    default: "false"
  remove_dotnet:
    description: "Remove .NET Files"
    required: false
    default: "false"
  remove_haskell:
    description: "Remove Haskell Files"
    required: false
    default: "false"
  remove_tool_cache:
    description: "Remove Tool Cache"
    required: false
    default: "false"
  remove_swap:
    description: "Remove Swap"
    required: false
    default: "false"
  remove_packages:
    description: "Remove Packages (Eg. azure-cli google-cloud-cli) Read the documentation for more information"
    required: false
    default: "false"
  remove_simultaneous:
    description: "Remove Packages Simultaneously (Eg. azure-cli google-cloud-cli) Read the documentation for more information"
    required: false
    default: "false"
  
  


# outputs:
#   saved-space:
#     description: "The amount of space saved"
#     value: ${{ steps.free-disk-space.outputs.saved-space }}

runs:
  using: "composite"
  steps:

    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - shell: bash
      name: "Free Disk Space"
      id: free-disk-space
      run: sudo -S sh main.sh
      env:
        PRINCIPAL_DIR: ${{ inputs.principal_dir }}
        ANDROID_FILES: ${{ inputs.remove_android }}
        DOTNET_FILES: ${{ inputs.remove_dotnet }}
        HASKELL_FILES: ${{ inputs.remove_haskell }}
        PACKAGES: ${{ inputs.remove_packages }}
        SIMULTANEOUS: ${{ inputs.remove_simultaneous }}
        TOOL_CACHE: ${{ inputs.remove_tool_cache }}
        SWAP_STORAGE: ${{ inputs.remove_swap }}