name: Free Disk Space (Ubuntu)
on:
  - push
  - workflow_dispatch

jobs:
  free-disk-space:
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space
        uses: endersonmenezes/free-disk-space@main
        with:
          remove_android: true
          remove_dotnet: true
          remove_haskell: true
          remove_packages: "azure-cli google-cloud-cli microsoft-edge-stable google-chrome-stable firefox dotnet-* temurin-* llvm-* mysql-* libllvm*"