name: Free Disk Space (Ubuntu)
on:
  - push
  - workflow_dispatch

jobs:
  free-disk-space:
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space
        uses: endersonmenezes/free-disk-space@main
        with:
          android: true